### PR TITLE
fix(actions,docker): allowing tag & push to multiple registries

### LINKED ISSUE #107: Push images to both DockerHub and Quay
After #89, `deisrel docker retag` will only push images to quay.io, not DockerHub. This issue is for also pushing to docker hub

### PR DESCRIPTION
**Pull request by arschles**
Fixes #107 

Adds a new `--registries` flag, which can be specified multiple times, to indicate all of the docker registries that the caller would like to pull from. For example:

```console
./deisrel docker retag --yes=false --ref=v2.0.0 --registries="index.docker.io" --registries="quay.io" workflow-2.1.0
```

# Associated [Documentation](https://github.com/deis/workflow) PR(s)

None required. This change will automatically pull from, tag and push to both quay.io and the docker hub

### CODE REVIEW

File: docker/image_test.go [hunk 1]
```diff
@@ -37,3 +41,15 @@ func TestParseImageFromName(t *testing.T) {
 		}
 	}
 }
+
+func TestParseImageFromRepoAndSha(t *testing.T) {
+	registries := []string{"", "quay.io"}
```
Comment (vdice) [inline docker/image_test.go]: `ParseImageFromRepoAndSha` could be passed `index.docker.io` as a registry, too, right?  Do we want to test that case? (covering logic that converts the actual string to `""`)

**Comment by vdice** [comment]
Unit test case suggested; otherwise LGTM

File: docker/image_test.go (hunk 1 above)
Comment (arschles) [inline docker/image_test.go]: ah, good catch. empty strings will be ignored and `index.docker.io` will be converted to an empty string. I need to add `index.docker.io` to test that behavior. thanks!

Comment (arschles) [inline docker/image_test.go]: fixed in https://github.com/deis/deisrel/pull/109/commits/aa839f71014a0ca61d31c0714a2b172b68c37630
