### PR TITLE
fix(main.go): change GITHUB_TOKEN to GITHUB_ACCESS_TOKEN

### LINKED ISSUE #41: GITHUB_TOKEN should be GITHUB_ACCESS_TOKEN

### PR DESCRIPTION
**Pull request by arschles**
Fixes #41

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -13,7 +13,7 @@ import (
 var version = "0.0.0"
 
 func main() {
-	ghTkn := os.Getenv("GITHUB_TOKEN")
+	ghTkn := os.Getenv("GITHUB_ACCESS_TOKEN")
 	if ghTkn == "" {
 		log.Fatalf("'GITHUB_TOKEN' env var required")
```
Comment (vdice) [inline main.go]: can we rename this as well to `GITHUB_ACCESS_TOKEN`?

Comment (arschles) [inline main.go]: @vdice yup, renamed in https://github.com/deis/deisrel/pull/48/commits/431151cbcdde3906ac02283d6bc70a4e9cf72780
